[package]
name = "gfe-ebpf"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
publish.workspace = true

[dependencies]
thiserror = { workspace = true }

[target.'cfg(target_os = "linux")'.dependencies]
aya = { workspace = true }
rustix = { workspace = true }
tokio = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
