//! `Acceptor` end to end, in process: a rustls client and the acceptor talk
//! over an in-memory duplex pipe, with certificates generated by `rcgen`.

use gfe_config::{CertEntry, MinVersion};
use gfe_tls::{Acceptor, CertStore, HandshakeError, SniResolver, TlsInfo, server_config};
use rustls::pki_types::{CertificateDer, ServerName};
use std::path::PathBuf;
use std::sync::Arc;
use std::sync::atomic::{AtomicUsize, Ordering};
use tokio::io::{AsyncReadExt, AsyncWriteExt, DuplexStream};
use tokio_rustls::TlsConnector;
use tokio_rustls::client::TlsStream as ClientStream;
use tokio_rustls::server::TlsStream as ServerStream;

/// A self-signed certificate written to its own scratch directory.
struct TestCert {
    der: CertificateDer<'static>,
    entry: CertEntry,
}

impl TestCert {
    fn new(sni: &[&str], default: bool) -> Self {
        static NEXT: AtomicUsize = AtomicUsize::new(0);
        let names = if sni.is_empty() {
            vec!["placeholder.local".to_string()]
        } else {
            sni.iter().map(|name| name.to_string()).collect()
        };
        let cert = rcgen::generate_simple_self_signed(names).unwrap();
        let dir: PathBuf = std::env::temp_dir().join(format!(
            "gfe-tls-acceptor-{}-{}",
            std::process::id(),
            NEXT.fetch_add(1, Ordering::Relaxed)
        ));
        std::fs::create_dir_all(&dir).unwrap();
        let entry = CertEntry {
            sni: sni.iter().map(|name| name.to_string()).collect(),
            default,
            cert_file: dir.join("tls.crt"),
            key_file: dir.join("tls.key"),
        };
        std::fs::write(&entry.cert_file, cert.cert.pem()).unwrap();
        std::fs::write(&entry.key_file, cert.key_pair.serialize_pem()).unwrap();
        TestCert {
            der: cert.cert.der().clone(),
            entry,
        }
    }
}

/// The acceptor for a store of `certs` under `min_version`, and its resolver.
fn server(certs: &[&TestCert], min_version: MinVersion) -> (Acceptor, Arc<SniResolver>) {
    let entries: Vec<CertEntry> = certs.iter().map(|cert| cert.entry.clone()).collect();
    let resolver = Arc::new(SniResolver::new(CertStore::build(&entries).unwrap()));
    let config = server_config(resolver.clone(), min_version).unwrap();
    (Acceptor::new(Arc::new(config)), resolver)
}

/// A client trusting `certs`, offering `versions` and ALPN `h2`, `http/1.1`.
/// Its session cache is part of the config: connections made with the same
/// config may resume.
fn client(
    certs: &[&TestCert],
    versions: &[&'static rustls::SupportedProtocolVersion],
) -> TlsConnector {
    let mut roots = rustls::RootCertStore::empty();
    for cert in certs {
        roots.add(cert.der.clone()).unwrap();
    }
    let provider = Arc::new(rustls::crypto::ring::default_provider());
    let mut config = rustls::ClientConfig::builder_with_provider(provider)
        .with_protocol_versions(versions)
        .unwrap()
        .with_root_certificates(roots)
        .with_no_client_auth();
    config.alpn_protocols = vec![b"h2".to_vec(), b"http/1.1".to_vec()];
    TlsConnector::from(Arc::new(config))
}

type Handshake = (
    Result<(ServerStream<DuplexStream>, TlsInfo), HandshakeError>,
    std::io::Result<ClientStream<DuplexStream>>,
);

/// Run both sides of a handshake for `name` over an in-memory pipe.
async fn handshake(acceptor: &Acceptor, connector: &TlsConnector, name: &str) -> Handshake {
    let (client_io, server_io) = tokio::io::duplex(64 * 1024);
    let name = ServerName::try_from(name.to_string()).unwrap();
    tokio::join!(
        acceptor.accept(server_io),
        connector.connect(name, client_io)
    )
}

/// Send one message each way, which also makes the client read the session
/// tickets the server sent after the handshake.
async fn exchange(
    server: &mut ServerStream<DuplexStream>,
    client: &mut ClientStream<DuplexStream>,
) {
    let mut buf = [0u8; 4];
    server.write_all(b"ping").await.unwrap();
    server.flush().await.unwrap();
    client.read_exact(&mut buf).await.unwrap();
    assert_eq!(&buf, b"ping");
    client.write_all(b"pong").await.unwrap();
    client.flush().await.unwrap();
    server.read_exact(&mut buf).await.unwrap();
    assert_eq!(&buf, b"pong");
}

/// The server side of a handshake that must fail.
fn failure(result: Handshake) -> HandshakeError {
    match result.0 {
        Ok(_) => panic!("the handshake succeeded"),
        Err(error) => error,
    }
}

#[tokio::test]
async fn a_full_handshake_reports_what_it_negotiated() {
    let cert = TestCert::new(&["api.example.org"], false);
    let (acceptor, _) = server(&[&cert], MinVersion::Tls12);
    let connector = client(&[&cert], rustls::ALL_VERSIONS);

    let (server, client) = handshake(&acceptor, &connector, "API.example.org").await;

    let (_, info) = server.unwrap();
    client.unwrap();
    assert_eq!(info.sni.as_deref(), Some("api.example.org"));
    assert_eq!(info.version, "TLSv1.3");
    assert!(info.cipher.starts_with("TLS13_"), "{}", info.cipher);
    assert_eq!(info.alpn.as_deref(), Some("h2"));
    assert!(!info.resumed);
}

#[tokio::test]
async fn a_tls12_handshake_reports_tls12() {
    let cert = TestCert::new(&["api.example.org"], false);
    let (acceptor, _) = server(&[&cert], MinVersion::Tls12);
    let connector = client(&[&cert], &[&rustls::version::TLS12]);

    let (server, _) = handshake(&acceptor, &connector, "api.example.org").await;

    assert_eq!(server.unwrap().1.version, "TLSv1.2");
}

#[tokio::test]
async fn a_second_connection_with_the_same_client_is_resumed() {
    let cert = TestCert::new(&["api.example.org"], false);
    let (acceptor, _) = server(&[&cert], MinVersion::Tls12);
    let connector = client(&[&cert], rustls::ALL_VERSIONS);
    let (first_server, first_client) = handshake(&acceptor, &connector, "api.example.org").await;
    let (mut first_server, first_info) = first_server.unwrap();
    exchange(&mut first_server, &mut first_client.unwrap()).await;

    let (second_server, _) = handshake(&acceptor, &connector, "api.example.org").await;

    assert!(!first_info.resumed);
    assert!(second_server.unwrap().1.resumed);
}

#[tokio::test]
async fn a_tls12_client_is_refused_by_a_tls13_only_policy() {
    let cert = TestCert::new(&["api.example.org"], false);
    let (acceptor, _) = server(&[&cert], MinVersion::Tls13);
    let connector = client(&[&cert], &[&rustls::version::TLS12]);

    let error = failure(handshake(&acceptor, &connector, "api.example.org").await);

    assert_eq!(error.reason(), "peer_incompatible", "{error}");
}

#[tokio::test]
async fn plain_http_is_an_invalid_message() {
    let cert = TestCert::new(&["api.example.org"], false);
    let (acceptor, _) = server(&[&cert], MinVersion::Tls12);
    let (mut client_io, server_io) = tokio::io::duplex(64 * 1024);
    client_io
        .write_all(b"GET / HTTP/1.1\r\nHost: api.example.org\r\n\r\n")
        .await
        .unwrap();

    // `client_io` stays open: the failure is the bytes, not a close.
    let error = acceptor.accept(server_io).await.err().unwrap();

    assert_eq!(error.reason(), "invalid_message", "{error}");
}

#[tokio::test]
async fn a_client_closing_mid_handshake_is_client_closed() {
    let cert = TestCert::new(&["api.example.org"], false);
    let (acceptor, _) = server(&[&cert], MinVersion::Tls12);
    let (mut client_io, server_io) = tokio::io::duplex(64 * 1024);
    // Half of a real ClientHello, then the client goes away.
    let provider = Arc::new(rustls::crypto::ring::default_provider());
    let config = rustls::ClientConfig::builder_with_provider(provider)
        .with_safe_default_protocol_versions()
        .unwrap()
        .with_root_certificates(rustls::RootCertStore::empty())
        .with_no_client_auth();
    let name = ServerName::try_from("api.example.org").unwrap();
    let mut hello = Vec::new();
    rustls::ClientConnection::new(Arc::new(config), name)
        .unwrap()
        .write_tls(&mut hello)
        .unwrap();
    client_io
        .write_all(&hello[..hello.len() / 2])
        .await
        .unwrap();
    drop(client_io);

    let error = acceptor.accept(server_io).await.err().unwrap();

    assert_eq!(error.reason(), "client_closed", "{error}");
}

#[tokio::test]
async fn an_unknown_name_without_a_default_fails_and_is_counted() {
    let cert = TestCert::new(&["api.example.org"], false);
    let (acceptor, resolver) = server(&[&cert], MinVersion::Tls12);
    let connector = client(&[&cert], rustls::ALL_VERSIONS);

    let error = failure(handshake(&acceptor, &connector, "unknown.example.org").await);

    assert_eq!(error.reason(), "other", "{error}");
    assert_eq!(resolver.miss_count(), 1);
}

#[tokio::test]
async fn a_swapped_store_serves_the_next_handshake_and_spares_established_ones() {
    let old = TestCert::new(&["api.example.org"], false);
    let new = TestCert::new(&["api.example.org"], false);
    let (acceptor, resolver) = server(&[&old], MinVersion::Tls12);
    let connector = client(&[&old, &new], rustls::ALL_VERSIONS);
    let peer_certificate = |client: &ClientStream<DuplexStream>| {
        client.get_ref().1.peer_certificates().unwrap()[0].clone()
    };
    let (established_server, established_client) =
        handshake(&acceptor, &connector, "api.example.org").await;
    let (mut established_server, _) = established_server.unwrap();
    let mut established_client = established_client.unwrap();

    resolver.swap(CertStore::build(std::slice::from_ref(&new.entry)).unwrap());
    let (_, next_client) = handshake(&acceptor, &connector, "api.example.org").await;

    assert_eq!(peer_certificate(&established_client), old.der);
    assert_eq!(peer_certificate(&next_client.unwrap()), new.der);
    exchange(&mut established_server, &mut established_client).await;
}
